services:

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: bookstore-db
    restart: always
    environment:
      MYSQL_DATABASE: book-store
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: laravel
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  # Laravel Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookstore-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_KEY: base64:fbXfKHfhy8cx8HHMS+Jh8hiKlazJP1LUetzVNC9KPfQ=
      APP_DEBUG: true
      APP_URL: http://localhost:8000
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: book-store
      DB_USERNAME: laravel
      DB_PASSWORD: secret
      SANCTUM_STATEFUL_DOMAINS: localhost:3000
      SESSION_DOMAIN: localhost
    depends_on:
      - db

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bookstore-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    depends_on:
      - backend

volumes:
  db_data:
